"""本地生成模型栈（V3.0 M4.1，架构 §19.5.6 / 计划 M4.1、F-35、VNF-01、VNF-03）

Web 端本地生成通道：Qwen3-4B-Instruct GGUF 经 llama-cpp-python（纯 CPU，无 GPU/torch 依赖），
产出中英双语审核报告、英文 README 与分享迭代差异描述；CC+MCP 外部通道（glm 5.3）不经过本模块
（外部产物经 MCP ``submit_skill_artifact`` 回传 + 平台重放校验存档，F-36）。

设计与 :mod:`platform_mcp.skills.embedding`（M3 向量栈）同构：

- **权重离线分发**（VNF-03）：``settings.skill.llm_model_path`` 指向离线 GGUF 文件；非空且
  llama-cpp-python 可导入/加载时启用，任何异常（依赖缺失、权重不存在、加载失败）降级为不可用，
  绝不联网下载。
- **单槽信号量**：本地模型 CPU 推理串行化——事件循环层 ``asyncio.Semaphore(1)`` 排队 +
  线程层 ``threading.Lock`` 防并发推理同一 ``Llama`` 实例（VNF-01 性能有限，逐条生成）。
- **超时兜底**（VNF-01）：单次生成 ``asyncio.wait_for`` 超时（默认 60s，可按调用覆盖）即放弃
  本次结果（底层线程自然结束后释放线程锁），调用方捕获 :class:`LlmGenerationError` 走确定性模板。
- **进程级单例**：``get_llm_provider()`` 选定后缓存（静态配置，切换权重需重启，§19.5.2）；
  ``reset_llm_provider()`` 为测试钩子。

产物来源留痕（``pmcp_skill_version.generated_by``，F-35）：

- ``template``：确定性模板兜底（M2 以来默认）；
- ``model``：本地 Qwen3-4B 生成（Web 通道，本模块）；
- ``external``：MCP 通道外部大模型（glm 5.3）回传产物（ecosystem 工具层写入）。

性能提示（M4.4，F-35「全程提示」）：本地模型产物与差异描述附带固定提示文案
「本地模型生成，性能有限，建议使用外部大模型（CC+MCP 通道）」。
"""

from __future__ import annotations

import asyncio
import threading

from loguru import logger

from platform_mcp.config import get_settings

#: 本地模型产物来源标记（pmcp_skill_version.generated_by 值域，F-35）
GENERATED_BY_MODEL = "model"
#: MCP 外部大模型回传产物来源标记（F-36）
GENERATED_BY_EXTERNAL = "external"

#: 性能有限提示（M4.4：本地模型产物/差异描述全程附带；Web 与 MCP 双端共用同一文案口径）
PERFORMANCE_HINT_ZH = "本地模型生成，性能有限，建议使用外部大模型（CC+MCP 通道）"
PERFORMANCE_HINT_EN = (
    "Generated by the local model with limited performance; "
    "an external large model (CC+MCP channel) is recommended"
)


class LlmGenerationError(RuntimeError):
    """本地生成失败（Provider 不可用 / 超时 / 推理异常 / 空输出）。

    调用方捕获后走确定性模板兜底（:mod:`platform_mcp.skills.versioning`），保证链路可用（F-35）。
    """


class LlmProvider:
    """文本生成器（当前仅 Qwen3 llama-cpp 单实现；接口留出后续本地栈扩展）。"""

    name: str = "base"

    @property
    def available(self) -> bool:
        """是否可用（权重/依赖缺失时为 False，调用方走模板兜底）。"""
        return False

    async def generate(
        self,
        prompt: str,
        *,
        max_tokens: int | None = None,
        timeout_seconds: float | None = None,
    ) -> str:
        """按 prompt 生成文本（单槽排队 + 超时兜底）。失败抛 :class:`LlmGenerationError`。"""
        raise LlmGenerationError(f"{self.name} 未实现 generate")


class QwenLlamaCppProvider(LlmProvider):
    """Qwen3-4B-Instruct GGUF 经 llama-cpp-python（纯 CPU int4 量化）。

    仅当显式配置离线权重路径且 llama-cpp-python 可导入/加载时可用；任何异常均降级为不可用
    （``get_llm_provider()`` 返回 None，调用方走模板），绝不联网下载（VNF-03）。

    并发口径（VNF-01）：

    - 事件循环层：单槽信号量（同一运行 loop 内严格串行排队；跨 loop 自动重建——
      pytest-asyncio 每用例独立 loop，进程内语义不变）；
    - 线程层：``threading.Lock`` 保证同一 ``Llama`` 实例不被并发推理（超时放弃的协程
      底层线程继续持锁至推理自然结束，后续请求在锁上排队而非崩溃）。
    """

    name = "qwen3-llama-cpp"

    def __init__(
        self,
        model_path: str,
        *,
        model_name: str = "Qwen3-4B-Instruct-GGUF",
        n_ctx: int = 8192,
        timeout_seconds: float = 60.0,
        max_tokens: int = 1024,
    ) -> None:
        self._model_path = model_path
        self._model_name = model_name
        self._n_ctx = n_ctx
        self._timeout = float(timeout_seconds)
        self._max_tokens = max_tokens
        self._model: object | None = None
        self._available = False
        self._thread_lock = threading.Lock()
        self._semaphore: asyncio.Semaphore | None = None
        self._semaphore_loop: asyncio.AbstractEventLoop | None = None
        try:
            from llama_cpp import Llama

            self._model = Llama(model_path=model_path, n_ctx=n_ctx, verbose=False)
            self._available = True
            logger.info(
                "本地生成模型就绪：{}（llama-cpp-python，n_ctx={}，权重={}）",
                model_name, n_ctx, model_path,
            )
        except Exception as exc:  # llama-cpp-python 缺失 / 权重不可用 → 降级（不联网，VNF-03）
            logger.warning("本地生成模型不可用（{}），生成链路走确定性模板兜底", exc)
            self._model = None
            self._available = False

    @property
    def available(self) -> bool:
        return self._available

    def _slot(self) -> asyncio.Semaphore:
        """当前事件循环关联的单槽信号量（跨 loop 自动重建，见类 docstring 并发口径）。"""
        loop = asyncio.get_running_loop()
        if self._semaphore is None or self._semaphore_loop is not loop:
            self._semaphore = asyncio.Semaphore(1)
            self._semaphore_loop = loop
        return self._semaphore

    def _generate_sync(self, prompt: str, max_tokens: int) -> str:
        """同步推理（线程层持锁串行；chat 模板取 GGUF 内置 Qwen3 模板）。"""
        with self._thread_lock:
            if self._model is None:  # pragma: no cover - 构造失败时 available=False 不会进入
                raise LlmGenerationError("Llama 实例未加载")
            chat_fn = getattr(self._model, "create_chat_completion")
            result = chat_fn(
                messages=[{"role": "user", "content": prompt}],
                max_tokens=max_tokens,
                temperature=0.3,
            )
        choices = (result or {}).get("choices") or []
        if not choices:
            raise LlmGenerationError("本地模型返回空 choices")
        content = ((choices[0].get("message") or {}).get("content")) or ""
        text = str(content).strip()
        if not text:
            raise LlmGenerationError("本地模型返回空输出")
        return text

    async def generate(
        self,
        prompt: str,
        *,
        max_tokens: int | None = None,
        timeout_seconds: float | None = None,
    ) -> str:
        if not self._available:
            raise LlmGenerationError(f"{self._model_name} 不可用（权重/依赖缺失）")
        timeout = float(timeout_seconds if timeout_seconds is not None else self._timeout)
        tokens = int(max_tokens if max_tokens is not None else self._max_tokens)
        try:
            async with self._slot():
                return await asyncio.wait_for(
                    asyncio.to_thread(self._generate_sync, prompt, tokens),
                    timeout=timeout,
                )
        except LlmGenerationError:
            raise
        except asyncio.TimeoutError as exc:
            raise LlmGenerationError(f"本地生成超时（>{timeout:.0f}s），放弃本次结果") from exc
        except Exception as exc:  # 推理异常 / 线程池异常 → 模板兜底
            raise LlmGenerationError(f"本地生成失败：{exc}") from exc


_provider: QwenLlamaCppProvider | None = None
_provider_resolved = False


def get_llm_provider() -> QwenLlamaCppProvider | None:
    """返回进程级单例本地生成 Provider（权重就绪时非 None；缺失返回 None 走模板）。

    选定后缓存（含「不可用」结论），避免每次生成重复尝试加载权重；静态配置口径下
    切换 ``settings.skill.llm_model_path`` 需重启进程（§19.5.2）。
    """
    global _provider, _provider_resolved
    if _provider_resolved:
        return _provider
    s = get_settings().skill
    if s.llm_model_path:
        _provider = QwenLlamaCppProvider(
            s.llm_model_path,
            model_name=s.llm_model_name,
            n_ctx=s.llm_n_ctx,
            timeout_seconds=float(s.llm_timeout_seconds),
            max_tokens=s.llm_max_tokens,
        )
        if not _provider.available:
            _provider = None
    else:
        _provider = None
    _provider_resolved = True
    logger.info("本地生成 Provider 选定：{}", _provider.name if _provider else "（无，模板兜底）")
    return _provider


def reset_llm_provider() -> None:
    """清空单例结论（测试用：切换 settings 后重新选定 provider）。"""
    global _provider, _provider_resolved
    _provider = None
    _provider_resolved = False


def llm_available() -> bool:
    """本地生成是否可用（权重就绪；False 时调用方直接走模板，不进入重试）。"""
    provider = get_llm_provider()
    return provider is not None and provider.available


async def llm_generate(
    prompt: str,
    *,
    max_tokens: int | None = None,
    timeout_seconds: float | None = None,
) -> str:
    """异步生成便捷入口：Provider 缺失/失败抛 :class:`LlmGenerationError`（调用方模板兜底）。"""
    provider = get_llm_provider()
    if provider is None:
        raise LlmGenerationError("本地生成模型未配置（settings.skill.llm_model_path 为空）")
    return await provider.generate(prompt, max_tokens=max_tokens, timeout_seconds=timeout_seconds)


__all__ = [
    "GENERATED_BY_EXTERNAL",
    "GENERATED_BY_MODEL",
    "PERFORMANCE_HINT_EN",
    "PERFORMANCE_HINT_ZH",
    "LlmGenerationError",
    "LlmProvider",
    "QwenLlamaCppProvider",
    "get_llm_provider",
    "llm_available",
    "llm_generate",
    "reset_llm_provider",
]
