"""initial_tables

Revision ID: ba0102b846dd
Revises: 
Create Date: 2026-06-05 18:04:07.486052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba0102b846dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pmcp_audit_log',
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='全链路追踪标识'),
    sa.Column('request_id', sa.String(length=64), nullable=True, comment='请求唯一标识'),
    sa.Column('operator', sa.String(length=64), nullable=True, comment='操作人'),
    sa.Column('skill_name', sa.String(length=64), nullable=True, comment='Skill 名称'),
    sa.Column('tool_name', sa.String(length=64), nullable=True, comment='Tool 名称'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='资源类型'),
    sa.Column('resource_id', sa.String(length=128), nullable=True, comment='资源标识'),
    sa.Column('env_code', sa.String(length=32), nullable=True, comment='环境标识'),
    sa.Column('request_summary', sa.Text(), nullable=True, comment='请求摘要'),
    sa.Column('result_status', sa.String(length=32), nullable=True, comment='结果状态(success/fail/error)'),
    sa.Column('risk_level', sa.String(length=16), nullable=True, comment='风险等级(LOW/MEDIUM/HIGH/CRITICAL)'),
    sa.Column('error_code', sa.String(length=32), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True, comment='结束时间'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='耗时毫秒'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展数据(JSONB)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='审计日志'
    )
    op.create_table('pmcp_crypto_operation_log',
    sa.Column('operator', sa.String(length=64), nullable=True, comment='操作人'),
    sa.Column('operation_type', sa.String(length=32), nullable=True, comment='操作类型(encrypt/decrypt)'),
    sa.Column('datasource_code', sa.String(length=64), nullable=True, comment='关联数据源编码'),
    sa.Column('algorithm', sa.String(length=32), nullable=True, comment='算法(AES-256-GCM/AES-256-CBC)'),
    sa.Column('result_status', sa.String(length=32), nullable=True, comment='结果状态'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='加解密操作日志'
    )
    op.create_table('pmcp_datasource',
    sa.Column('datasource_code', sa.String(length=64), nullable=False, comment='数据源编码'),
    sa.Column('datasource_name', sa.String(length=128), nullable=False, comment='数据源名称'),
    sa.Column('db_type', sa.String(length=32), nullable=False, comment='数据库类型(oracle/mysql)'),
    sa.Column('host', sa.String(length=256), nullable=False),
    sa.Column('port', sa.SmallInteger(), nullable=False),
    sa.Column('instance_name', sa.String(length=128), nullable=True, comment='实例名/SID'),
    sa.Column('username', sa.String(length=128), nullable=False, comment='连接用户名'),
    sa.Column('encrypted_password', sa.String(length=512), nullable=True, comment='AES密文密码'),
    sa.Column('env_code', sa.String(length=32), nullable=False, comment='环境标识(DEV/TEST/PROD)'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1-启用 0-禁用'),
    sa.Column('connection_string', sa.String(length=512), nullable=True, comment='完整连接串'),
    sa.Column('max_concurrent', sa.SmallInteger(), server_default='5', nullable=False, comment='最大并发数'),
    sa.Column('query_timeout', sa.SmallInteger(), server_default='300', nullable=False, comment='查询超时(秒)'),
    sa.Column('extra_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展配置'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datasource_code'),
    comment='数据源配置'
    )
    op.create_table('pmcp_mcp_call_log',
    sa.Column('trace_id', sa.String(length=64), nullable=True, comment='全链路追踪标识'),
    sa.Column('tool_name', sa.String(length=64), nullable=True, comment='Tool 名称'),
    sa.Column('caller', sa.String(length=128), nullable=True, comment='调用方(Claude Code)'),
    sa.Column('datasource_code', sa.String(length=64), nullable=True, comment='数据源编码'),
    sa.Column('env_code', sa.String(length=32), nullable=True, comment='环境标识'),
    sa.Column('input_summary', sa.Text(), nullable=True, comment='输入摘要'),
    sa.Column('output_summary', sa.Text(), nullable=True, comment='输出摘要'),
    sa.Column('result_status', sa.String(length=32), nullable=True, comment='结果状态'),
    sa.Column('error_code', sa.String(length=32), nullable=True, comment='错误码'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='错误信息'),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True, comment='耗时毫秒'),
    sa.Column('confirm_token', sa.String(length=128), nullable=True, comment='确认令牌'),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展数据'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='MCP 调用日志'
    )
    op.create_table('pmcp_permission',
    sa.Column('permission_name', sa.String(length=128), nullable=False, comment='权限名称'),
    sa.Column('permission_code', sa.String(length=128), nullable=False, comment='权限标识'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='资源类型(menu/button/api)'),
    sa.Column('resource_path', sa.String(length=256), nullable=True, comment='资源路径'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父权限ID'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1-启用 0-禁用'),
    sa.Column('sort_order', sa.SmallInteger(), server_default='0', nullable=True, comment='排序'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission_code'),
    comment='权限定义'
    )
    op.create_table('pmcp_role',
    sa.Column('role_name', sa.String(length=64), nullable=False, comment='角色名称'),
    sa.Column('role_code', sa.String(length=64), nullable=False, comment='角色标识'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1-启用 0-禁用'),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_code'),
    comment='角色信息'
    )
    op.create_table('pmcp_skill',
    sa.Column('skill_code', sa.String(length=64), nullable=False, comment='Skill 编码'),
    sa.Column('skill_name', sa.String(length=128), nullable=False, comment='Skill 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='Skill 描述'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='状态 1-启用 0-禁用'),
    sa.Column('register_method', sa.String(length=32), nullable=True, comment='注册方式(decorator/form/upload)'),
    sa.Column('tool_count', sa.SmallInteger(), server_default='0', nullable=False, comment='Tool 数量'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_code'),
    comment='Skill 注册信息'
    )
    op.create_table('pmcp_system_config',
    sa.Column('config_key', sa.String(length=128), nullable=False, comment='配置键'),
    sa.Column('config_value', sa.Text(), nullable=True, comment='配置值'),
    sa.Column('config_type', sa.String(length=32), nullable=True, comment='值类型(string/int/json/bool)'),
    sa.Column('description', sa.String(length=512), nullable=True, comment='配置说明'),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1-启用 0-禁用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    comment='系统参数配置'
    )
    op.create_table('pmcp_user',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('nickname', sa.String(length=64), nullable=True),
    sa.Column('status', sa.SmallInteger(), server_default='1', nullable=False, comment='1-启用 0-禁用'),
    sa.Column('remark', sa.String(length=512), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    comment='用户信息'
    )
    op.create_table('pmcp_datasource_permission',
    sa.Column('datasource_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True, comment='授权用户'),
    sa.Column('role_id', sa.BigInteger(), nullable=True, comment='授权角色'),
    sa.Column('permission_type', sa.String(length=32), nullable=False, comment='权限类型(query/manage)'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['datasource_id'], ['pmcp_datasource.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['pmcp_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pmcp_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='数据源权限关系'
    )
    op.create_table('pmcp_role_permission',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['pmcp_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['pmcp_role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='角色权限关系'
    )
    op.create_table('pmcp_user_role',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('inserted_by', sa.String(length=64), nullable=True),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['pmcp_role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['pmcp_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='用户角色关系'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pmcp_user_role')
    op.drop_table('pmcp_role_permission')
    op.drop_table('pmcp_datasource_permission')
    op.drop_table('pmcp_user')
    op.drop_table('pmcp_system_config')
    op.drop_table('pmcp_skill')
    op.drop_table('pmcp_role')
    op.drop_table('pmcp_permission')
    op.drop_table('pmcp_mcp_call_log')
    op.drop_table('pmcp_datasource')
    op.drop_table('pmcp_crypto_operation_log')
    op.drop_table('pmcp_audit_log')
    # ### end Alembic commands ###
